# Generated by Django 4.1.1 on 2022-10-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aeibt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_present", models.BooleanField(default=False)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SemesterCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aeibt.course"
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aeibt.semester"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SemesterCourseEnroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                (
                    "semester_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aeibt.semestercourse",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aeibt.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.CharField(max_length=100)),
                ("teacher_name", models.CharField(max_length=200)),
                ("teacher_address", models.CharField(max_length=500)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aeibt.department",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TakenCourse",
        ),
        migrations.AddField(
            model_name="semestercourse",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="aeibt.teacher"
            ),
        ),
        migrations.AddField(
            model_name="courseclass",
            name="semester_course_enroll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="aeibt.semestercourseenroll",
            ),
        ),
    ]
